// Values are generated by the MILP, never a second hand-maintained trajectory.
(() => {
  const data = window.FIGURE_RESULTS;
  if (!data) return; // Static SVGs and summary values still work without JS.
  const comparison = data.comparison;
  const checks = data.solution.checks;
  const residual = (value, unit) => `${value < 1e-6 ? '< 10⁻⁶' : value.toExponential(2)} ${unit}`;
  const values = {
    'rms-error': `${comparison.rms_node_error_m.toFixed(0)} m`,
    'max-error': `${comparison.max_node_error_m.toFixed(0)} m`,
    'relative-error': `${comparison.max_error_percent_initial_altitude.toFixed(3)}%`,
    'position-residual': residual(checks.terminal_position_error_m, 'm'),
    'velocity-residual': residual(checks.terminal_velocity_error_m_s, 'm/s'),
    'dynamics-residual': residual(checks.max_position_dynamics_residual_m, 'm'),
    'mip-gap': checks.mip_relative_gap < 1e-8 ? '< 10⁻⁸' : checks.mip_relative_gap.toExponential(2),
    'norm-range': `${checks.min_thrust_m_s2.toFixed(4)}–${checks.max_thrust_m_s2.toFixed(4)} m/s²`,
    'norm-violation': `${checks.upper_norm_violation_m_s2.toFixed(4)} m/s²`,
    'searched-time': `${data.time_search.best.tf_s.toFixed(1)} s`,
  };
  document.querySelectorAll('[data-result]').forEach((element) => {
    const value = values[element.dataset.result];
    if (value !== undefined) element.textContent = value;
  });
})();
